---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, eval=FALSE}
########## A Demonstration of the Two-Part Model with Nahmint Data #############

suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(statmod))
suppressPackageStartupMessages(library(boot))
suppressPackageStartupMessages(library(MASS))

```


# 1. Gamma GLM

```{r}
Nahmint <- read.csv("../data/Nahmint.all.csv", stringsAsFactors=FALSE)
Nahmint_pos <- Nahmint %>% 
  mutate(biomass.m2=if_else(biomass.m2==0, 0.01, biomass.m2))

## 1. Exploratory plots
### Histogram of biomass for all five streams - right skewed
Nahmint_pos %>% 
  ggplot() +
  geom_histogram(aes(x=biomass.m2), color="black") +
  labs(x="Biomass (per square meter)", y="Count") +
  theme_bw()
ggsave("../Plots/replaced.pdf", width=6, height=3)

### Scatterplots of biomass versus three predictors respectively
Nahmint_pos %>%
  ggplot() +
  geom_point(aes(x=gradient, y=biomass.m2), color="steelblue", alpha=0.7) +
  ggsave("../Plots/biomass_vs_gradient.png", width=3, height = 3)

Nahmint_pos %>%
  ggplot() +
  geom_point(aes(x=BFW.m, y=biomass.m2), color="steelblue", alpha=0.7) +
  ggsave("../Plots/biomass_vs_BFW.png", width=3, height = 3)

Nahmint_pos %>%
  ggplot() +
  geom_point(aes(x=wood.m2, y=biomass.m2), color="steelblue", alpha=0.7) +
  ggsave("../Plots/biomass_vs_wood.png", width=3, height = 3)
  

## 2. Gamma GLM with log link 
fit.gamma <- glm(biomass.m2~gradient+BFW.m+wood.m2, data=Nahmint_pos, 
                 family=Gamma(link=log), maxit=1000000)
### Get maximum likelihood estimates on shape and scale parameters:
a <- gamma.shape(fit.gamma)$alpha  # from MASS library
b <- mean(predict(fit.gamma, type="response"))/a
summary(fit.gamma, dispersion = 1/a)

## A side note: Inverse Gaussian with log link (doesn't converge for the given dataset)
fit.ig <- glm(biomass.m2~gradient+BFW.m+wood.m2, data=Nahmint_pos, 
              family=inverse.gaussian(link=log))
summary(fit.ig)

## 3. Check if the response y follows a Gamma distribution
### Overlay the fitted density curve on top of the histogram of the observed response:
binwidth <- 0.08
n <- Nahmint_pos %>% nrow()
Nahmint_pos %>% 
  ggplot(aes(x=biomass.m2)) +
  geom_histogram(binwidth=binwidth, fill="white", color="black") +
  stat_function(fun=function(x) dgamma(x, shape=a, scale=b)*n*binwidth, color="red") +
  theme_bw()
ggsave("histgamma.pdf", width=6, height=3)


## 4. Diagnostics on Gamma GLM (using `boot` library)
diag <- glm.diag(fit.gamma)
pdf("diaggamma.pdf")
glm.diag.plots(fit.gamma, diag)
dev.off()


## 5. Diagnostics on link function
mu <- predict(fit.gamma,type="response")
z <- predict(fit.gamma) + (Nahmint_pos$density.m2-mu)/mu
df_gamma_link <- data.frame(mu=mu, z=z)

df_gamma_link %>% 
  ggplot(aes(y=z, x=predict(fit.gamma))) +
  geom_point() +
  labs(x="Linear predictor", y="Linearized Response") +
  theme_bw()
ggsave("linkfunc.pdf", width=6, height=3)


### Scatterplots of linearized biomass versus three predictors respectively
Nahmint_pos %>%
  ggplot() +
  geom_point(aes(x=gradient, y=z), color="steelblue", alpha=0.7) +
  ylab("Linearized biomass") +
  ggsave("../Plots/linearized_biomass_vs_gradient.png", width=3, height = 3)

Nahmint_pos %>%
  ggplot() +
  geom_point(aes(x=BFW.m, y=z), color="steelblue", alpha=0.7) +
  ylab("Linearized biomass") +
  ggsave("../Plots/linearized_biomass_vs_BFW.png", width=3, height = 3)

Nahmint_pos %>%
  ggplot() +
  geom_point(aes(x=wood.m2, y=z), color="steelblue", alpha=0.7) +
  ylab("Linearized biomass") +
  ggsave("../Plots/linearized_biomass_vs_wood.png", width=3, height = 3)


```

# 2. Two-Part Model

```{r}
## Partition the original dataset into training and test set (for prediction):
Nahmint_train <- Nahmint %>% slice_sample(n=300)
Nahmint_test <- setdiff(Nahmint, Nahmint_train)

## Label observations: if density or biomass is 0, label it as 0; otherwise, label as 1.
## This step is a preparation for fitting the logistic regression.
Nahmint_train <- Nahmint_train %>% mutate(label=if_else(biomass.m2==0, 0, 1)) 

######### Two-parts Model ###########

## 1. Part 1: binomial/logistic regression model (on binary responses)
fit.binomial <- glm(label~gradient+BFW.m+wood.m2, data=Nahmint_train, 
                    family=binomial(link=logit))
summary(fit.binomial)


## 2. Part 2: Gamma GLM with log link (only on positive responses)
fit.gamma <- glm(biomass.m2~gradient+BFW.m+wood.m2, data=subset(Nahmint_train, label==1), 
                 family=Gamma(link=log))
summary(fit.gamma)

## inverse gamma
# fit.ig <- glm(density.m2~gradient+BFW.m+wood.m2, data=subset(Nahmint_train, label==1), 
#                 family=inverse.gaussian(link=log))

```


```{r}
# 3. Prediction on the test set

## Compute P(Y_0 > 0 | X):
pred.binomial <- predict(fit.binomial, Nahmint_test, type = "response")

## Compute E(Y | Y > 0, X)
pred.gamma <- predict(fit.gamma, Nahmint_test, type = "response")

## Compute E(Y) = P(Y_0 > 0 | X) * E(Y | Y > 0, X)
pred <- pred.binomial*pred.gamma

## Extract observed biomass from the test dataset:
y <- Nahmint_test$biomass.m2

## Boxplot on observed biomass and predicted mean biomass
df <- data.frame(observed=y, predicted=pred)
ggpaired(df, cond1="observed", cond2="predicted", line.color="gray") +
  labs(y="Biomass per square meter", x="")
ggsave("pred.pdf", width=6, height=6)

## Density curves on observed biomass and predicted mean biomass
p.dat <- data.frame(response=c(y, pred), lab = c(rep("Observed", n), rep("Predicted", n)))
p.dat %>% 
  ggplot(aes(x=response, col=lab)) + 
  geom_density() +
  labs(x="Biomass", y="Density") +
  theme_bw()
ggsave("pred1.pdf", width=6, height=3)



# 4. Predictive Simulation:
## Simulate distribution of biomass for the test dataset and compare
## the simulated distribution with the true distirbution

n <- nrow(Nahmint_test)

## `d` is the predicted Bernoulli response based on simulation:
d <- rbinom(n, size=1, prob=pred.binomial) 
## `a` and `b` are shape and scale parameter for Gamma distribution, respectively
a <- gamma.shape(fit.gamma)$alpha 
b <- pred.gamma/a
## `y.gamma` is the predicted Gamma response based on simulation:
y.gamma <- rgamma(n, shape=a , scale=b)

## Computed predicted biomass based on simulation:
y.pred <- d*y.gamma

## Compare observed density and simulated density curve on biomass
p.dat <- data.frame(response=c(y, y.pred), lab = c(rep("Observed", n), rep("Simulated", n)))

p.dat %>% 
  ggplot(aes(x=response, col=lab)) + 
  geom_density() +
  labs(x="Biomass", y="Density") +
  theme_bw()
ggsave("sim_pred.pdf", width=6, height=3)

```

